dset_name: "@OPTIONS(shapenet10)"
pcd_root: "/path/to/pcd/dset"
splits: ["train", "val", "test"]

num_points_pcd: 2048
vox_res: 64

num_required_train_shapes: 100_000

num_points_fitting: 10_000
num_parallel_mlps: 16

mlp:
  hidden_dim: 512
  num_hidden_layers: 4
  init_path: "../inits/in3_out1_h512_l4.pt"

num_steps: 500
lr: 1e-4

out_root: "/path/where/to/save/inrs"
